// Generated by IntelliJ-IDEA Scala plugin.
// Adds settings when starting sbt from IDEA.
// Manual changes to this file will be lost.
if (java.lang.System.getProperty("idea.runid", "false") == "2018.2.1+4-88400d3f") scala.collection.Seq(
resolvers += Resolver.file("intellij-scala-plugin", file(raw"/home/mark/.IntelliJIdea2018.3/config/plugins/Scala/repo"))(Resolver.ivyStylePatterns),
addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "2018.2.1+4-88400d3f"),
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2018.3")
) else scala.collection.Seq.empty